df <- read.table("../household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", nrows= 1000000, stringsAsFactors=FALSE)
df$Time <- strptime(paste(df$Date, df$Time), "%d/%m/%Y %H:%M:%S")
df$Date <- as.Date(df$Date, "%d/%m/%Y")
dateRange <- as.Date(c("2007-02-01", "2007-02-02"), "%Y-%m-%d")
df <- subset(df, Date %in% dateRange)
head(df)
plot(df$Time, df$Global_active_power, type = "l", ylab="Global Active Power (kilowatts)", xlab = "")
dev.copy(png, file = "plot2.png", width = 480, height = 480)
dev.off()